### ISSUE TITLE
Getting error while executing curl -L "https://raw.githubusercontent.com/Be-Secure/BeSman/dist/dist/get.besman.io" | bash

### ISSUE THREAD

**Issue by anilsingla** [Be-Secure/BeSman#125]
gets error:

bash: line 25: syntax error near unexpected token `fi'
bash: line 25: `fi'
bash: line 29: /root/.besman/bin/besman-init.sh: No such file or directory

while installing via bliman.

**Comment by asa1997** [comment]
Fixed by #127.

Will be in effect from next release.
