### ISSUE TITLE
bes list command is buggy

### ISSUE THREAD

**Issue by Aditi8007** [Be-Secure/BeSman#128]
###  ISSUE: 
While running ` bes list ` command ,below error is produced.
``` 
---------------------------------PLAYBOOKS--------------------------------------------------
Could not find /home/aditi/.besman/scripts/besman-get-playbook-details.py 
 ```
 ### INTRIM FIX
1.For resolving this issue clone below repository
`git clone https://github.com/Be-Secure/BeSman.git`
2.Then find out the script folder ` BeSman/src/main/bash/scripts ` And put it inside the `.besman`  folder in your pc.
> idealy  `.besman` folder should be found in your home directory

3.Try `bes list ` command in new terminal.
4.It should work now.

### CAUSE
besman init script is not cloning `scripts`  folder into `.besman` during BeSman installation.

### SOLUTION
Please modify the installation script accordingly.

**Comment by Aditi8007** [comment]
I have tried but still issue is getting.
plz find the attached screenshot in this conversation

**Comment by samirparhi-dev** [comment]
![besman_issue](https://github.com/Be-Secure/BeSman/assets/59992800/25536973-d48f-41b7-bda9-db5d85255b81)
FYI @asa1997 @asa1997 @harimohanr

**Comment by asa1997** [comment]
@Aditi8007 @samirparhi-dev The updated code will only be in effect after the release. In the mean time, you can do the following steps.

1. Clone besman.
2. cd BeSman
3. switch to master branch
4. Run `./quick_install.sh`
