### ISSUE TITLE
[Bug]: Misconfiguration in command  bes install -env <> -V <>

### ISSUE THREAD

**Issue by Aditi8007** [Be-Secure/BeSman#140]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://be-secure.github.io/Be-Secure/contribute.html) and wholeheartedly agree

### Description

1.While creating the Environment using command  `bes create -env druid-RT-env -V 0.0.1 basic` 
the config file created in /home/aditi8007/Envfiles/druid/0.0.1/besman-druid-RT-env-config.yaml (because I have given the default path should be `/$HOME/Envfiles`)
please find the evidence below

``` aditi8007@L-357009166:~$ bes create -env druid-RT-env -V 0.0.1 basic
Variable 'BESMAN_LOCAL_ENV' value updated to 'true'
Creating env file..
Creating new config file /home/aditi8007/Envfiles/druid/0.0.1/besman-druid-RT-env-config.yaml
Updating local list ```


### Expected behavior

While using `bes install -env druid-RT-env -V 0.0.1` 
I got the below text  in terminal window  :
` 3. Open the file /home/aditi8007/besman-druid-RT-env-config.yaml in an editor `

###Output should as below :

``` aditi8007@L-357009166:~$ bes install -env druid-RT-env -V 0.0.1
grep: warning: ? at start of expression
grep: warning: ? at start of expression
grep: warning: ? at start of expression
grep: warning: ? at start of expression
grep: warning: ? at start of expression
grep: warning: ? at start of expression
Sourcing default config parameters
Going with default lab association - Be-Secure Community Lab
Do you wish to change the lab association (y/n)?:y

1. Check if the file /home/aditi8007/besman-druid-RT-env-config.yaml exists in /home/aditi8007

2. If the file does not exist, run the below command to download the file

                wget -P $HOME https://raw.githubusercontent.com/Be-Secure/besecure-ce-env-repo/master/druid/0.0.1/besman-druid-RT-env-config.yaml

3. Open the file /home/aditi8007/Envfiles/druid/0.0.1/besman-druid-RT-env-config.yaml in an editor

         4. Edit the variables - BESMAN_LAB_NAME and BESMAN_LAB_TYPE ```
         

### Actual behavior

While using `bes install -env druid-RT-env -V 0.0.1` 
I should get the below text  in terminal window  :
` 3. Open the file /home/aditi8007/besman-druid-RT-env-config.yaml in an editor `
Because config file got created :  
` /home/aditi8007/Envfiles/druid/0.0.1/besman-druid-RT-env-config.yaml `
It should look like below:
```
aditi8007@L-357009166:~$ bes install -env druid-RT-env -V 0.0.1
grep: warning: ? at start of expression
grep: warning: ? at start of expression
grep: warning: ? at start of expression
grep: warning: ? at start of expression
grep: warning: ? at start of expression
grep: warning: ? at start of expression
Sourcing default config parameters
Going with default lab association - Be-Secure Community Lab
Do you wish to change the lab association (y/n):y

1. Check if the file /home/aditi8007/besman-druid-RT-env-config.yaml exists in /home/aditi8007

2. If the file does not exist, run the below command to download the file
wget -P $HOME https://raw.githubusercontent.com/Be-Secure/besecure-ce-env-repo/master/druid/0.0.1/besman-druid-RT-env-config.yaml

3. Open the file /home/aditi8007/besman-druid-RT-env-config.yaml in an editor
            
 4. Edit the variables - BESMAN_LAB_NAME and BESMAN_LAB_TYPE ```
             
  
  
         
         

### Steps to reproduce

1.`bes create -env druid-RT-env -V 0.0.1 basic`
2.`bes install -env druid-RT-env -V 0.0.1`

### Relevant screenshots

![Screenshot 2024-04-02 172949](https://github.com/Be-Secure/BeSman/assets/95067528/7b488115-69a7-4ad7-8ad9-5609af618212)

### Possible Solution

please adjust the scripts accordingly.

### Additional Information

```shell
FYI @samirparhi-dev
```

**Comment by Aditi8007** [comment]
FYI @samirparhi-dev

**Comment by asa1997** [comment]
@Aditi8007 Closing as issue is fixed
