### ISSUE TITLE
[BeSIP: 01] - Proposal to integrate code scanning tools in Be-Secure platform

### ISSUE THREAD

**Issue by jobyko** [Be-Secure/BeSman#16]
#### A .  Study of <securtiy_app>:<version>               #### [Learning part before besman integration]

 **Main points to be address at this point:**

-               1) How do one use <securtiy_app>
-               2) How do one configure <securtiy_app>

                          >  List of configuration files
                          >  Plans/ideas on extending functionality by writing extra rules

#### B.  Besman integration                                          #### [Actual integration]

**Main points to be address at this point:**

-              How to bring up <securtiy_app> inside BeSman
-             Setting up playbook for specific bes tech stack

                       Eg. Security assessment playbook - Java Spring 

Security assessment playbook skeleton: 

                    [
                       O/P 1 - Playbook execution Result - CodeQL.

                       O/P 2 - Playbook execution Result - WhiteSource Cure
                        .
                        .
                      O/P n - Playbook execution Result - <securtiy_app>
                    ]

#### C.  Additional topics

Design/spec for Be-Secure components/artifacts

**Comment by asa1997** [comment]
closing as outdated
