### ISSUE TITLE
TODO: Generalize the playbook file names

### ISSUE THREAD

**Issue by jobyko** [Be-Secure/BeSman#17]
Set all environment names in below format:

`bes-<cve-details>-<category-of-vulnerability>-<author>-playbook`

Inputs -> cve details, category, author

optional: environment name

**Comment by asa1997** [comment]
@jobyko I believe the env name should be required.

**Comment by jobyko** [comment]
@asa1997  
Expecting a model something like this 
bes-<cve-details>-<category-of-vulnerability>-<author>-<env-name>-playbook

**Comment by asa1997** [comment]
@jobyko should start with besman-**** instead of bes-****

**Comment by jobyko** [comment]
@asa1997 
besman-<cve-details>-<category-of-vulnerability>-<author>-<env-name>-playbook
Hope its fine now, eventhough initial discussion focused on 'bes-' prefix 

@sumodgeorge  @panickervinod

**Comment by asa1997** [comment]
The reason being besman-*** is that I am trying to use bes update command to pull down the playbook files as well and the update command recognises files only with besman- prefix.

**Comment by asa1997** [comment]
Closing as outdated
