### ISSUE TITLE
[Bug]: Command attest is throwing incorrect syntax

### ISSUE THREAD

**Issue by asa1997** [Be-Secure/BeSman#180]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://be-secure.github.io/Be-Secure/contribute.html) and wholeheartedly agree

### Description

When running the attest command, it is showing syntax error.

### Expected behaviour

Should attest.

### Actual behaviour

Command throws error when running with/without path parameter

### Steps to reproduce

`$ bes attest --file <file name>`

or

`$ bes attest --file <file name> --path <path>`

### Relevant screenshots

![image](https://github.com/Be-Secure/BeSman/assets/58501088/3a1b7af3-8c0c-4af0-8740-d66da192632b)

**Comment by anilsingla** [comment]
fixed in #181
